server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: live-events
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: user
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 5
      retry.backoff.ms: 1000

logging:
  level:
    com.example.sports: DEBUG